substitutions:
  name: "study-atom-echo"
  friendly_name: Study Atom Echo
  micro_wake_word_model: hey_jarvis
  media_player: media_player.study
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name_add_mac_suffix: false
api:
  encryption:
    key: ugRt/qQlJKYOuuTTNZ6xOvp3KgHPFMWSXUFXzXuotp4=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: homeassistant
    id: media_player_state
    name: "Media Player State"
    entity_id: ${media_player}

voice_assistant:
  speaker: !remove
  on_listening:
  - if:
      condition:
        text_sensor.state:
          id: media_player_state
          state: 'playing'
      then:
        - homeassistant.action:
            service: media_player.volume_mute
            data:
              entity_id: ${media_player}
  on_tts_end:
    - homeassistant.action:
        service: script.play_esphome_response
        data:
          media_player: ${media_player}
          media_content_id: !lambda 'return x;'
          

