substitutions:
  name: "study-atom-echo"
  friendly_name: Study Atom Echo
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ugRt/qQlJKYOuuTTNZ6xOvp3KgHPFMWSXUFXzXuotp4=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

voice_assistant:
  speaker: !remove
  noise_suppression_level: 4.0
  volume_multiplier: 4.0
  on_tts_end:
     - homeassistant.service:
         service: media_player.play_media
         data:
           entity_id: media_player.study
           media_content_id: !lambda 'return x;'
           media_content_type: music
           announce: "true"
